apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://stakater.github.io/stakater-charts
      chart: forecastle
      targetRevision: 1.0.159
      helm:
        valueFiles:
          - $values/apps/forecastle/values.yaml

    - repoURL: 'https://github.com/jkroepke/idp.git'
      targetRevision: init
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: forecastle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
