forecastle:
  config:
    namespaceSelector:
      any: true
  service:
    annotations: {}
    expose: "false"
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: localhost
        paths:
          - path: /
            pathType: Exact
          - path: /logo192.png
            pathType: Exact
          - path: /api/
            pathType: Prefix
          - path: /static/
            pathType: Prefix
