forecastle:
  config:
    namespaceSelector:
      any: true
    headerBackground:
    headerForeground:
    title: Internal Developer Platform Demo
    crdEnabled: false
  service:
    annotations: {}
    expose: "false"
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: localhost
        paths:
          - path: "^/$"
            pathType: ImplementationSpecific
          - path: /
            pathType: Exact
          - path: /logo192.png
            pathType: Exact
          - path: /api/
            pathType: Prefix
          - path: /static/
            pathType: Prefix
