apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kratix-promises
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/jkroepke/idp.git
        revision: init
        directories:
          - path: kratix/promises/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: kratix-promises
      sources:
        - repoURL: https://github.com/jkroepke/idp.git
          targetRevision: init
          path: '{{.path.path}}'
          directory:
            recurse: true
            include: 'promise.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'default'
