controller:
  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443
  service:
    type: ClusterIP
  admissionWebhooks:
    failurePolicy: Ignore
    patch:
      enabled: false
    certManager:
      enabled: true
  updateStrategy:
    type: Restart
