apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3
spec:
  compositeTypeRef:
    apiVersion: crossplane.jkroepke.de/v1alpha1
    kind: s3
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: fn-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: bucket
            base:
              apiVersion: s3.aws.m.upbound.io/v1beta1
              kind: Bucket
              spec:
                forProvider:
                  region: eu-central-1
                  tags:
                    Name: aws-ba-crossplane-test
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.providerConfigRef.kind
                toFieldPath: spec.providerConfigRef.kind
              - type: FromCompositeFieldPath
                fromFieldPath: spec.providerConfigRef.name
                toFieldPath: spec.providerConfigRef.name
              - type: ToCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: status.resourceName
          - name: versioning
            base:
              apiVersion: s3.aws.m.upbound.io/v1beta1
              kind: BucketVersioning
              spec:
                forProvider:
                  region: eu-central-1
                  versioningConfiguration:
                    status: Enabled
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: status.resourceName
                toFieldPath: spec.forProvider.bucketRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.providerConfigRef.kind
                toFieldPath: spec.providerConfigRef.kind
              - type: FromCompositeFieldPath
                fromFieldPath: spec.providerConfigRef.name
                toFieldPath: spec.providerConfigRef.name
          - name: policy
            base:
              apiVersion: s3.aws.m.upbound.io/v1beta1
              kind: BucketPolicy
              spec:
                forProvider:
                  region: eu-central-1
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: status.resourceName
                toFieldPath: spec.forProvider.bucketRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.providerConfigRef.kind
                toFieldPath: spec.providerConfigRef.kind
              - type: FromCompositeFieldPath
                fromFieldPath: spec.providerConfigRef.name
                toFieldPath: spec.providerConfigRef.name
              - type: CombineToComposite
                combine:
                  variables:
                    - fromFieldPath: status.resourceName
                  strategy: string
                  string:
                    fmt: '{"Version":"2012-10-17","Statement":[{"Effect":"Deny","Principal":"*","Action":["s3:GetObject"],"Resource":["arn:aws:s3:::%s/*"]}]}'
                toFieldPath: spec.forProvider.policy
    - step: kratix-health-record-bucket
      functionRef:
        name: fn-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: platform.kratix.io/v1alpha1
            kind: HealthRecord
            metadata:
              name: {{ .observed.composite.resource.metadata.name }}-bucket
              annotations:
                {{ setResourceNameAnnotation "health-record-bucket" }}
                {{- if eq (.observed.resources.bucket | getResourceCondition "Synced").Status "True" }}
                gotemplating.fn.crossplane.io/ready: "True"
                {{- end }}
            data:
              {{- .observed.composite.resource.spec.kratix | toYaml | nindent 2 }}
              {{- if eq (.observed.resources.bucket | getResourceCondition "Synced").Status "True" }}
              state: ready
              {{- else }}
              state: degraded
              {{- end }}
              lastRun: {{ now | unixEpoch }}
              {{- with .observed.resources.bucket.status.atProvider }}
              details:
                {{- . | toYaml | nindent 4 }}
              {{- end }}
    - step: kratix-health-record-versioning
      functionRef:
        name: fn-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: platform.kratix.io/v1alpha1
            kind: HealthRecord
            metadata:
              name: {{ .observed.composite.resource.metadata.name }}-versioning
              annotations:
                {{ setResourceNameAnnotation "health-record-versioning" }}
                {{- if eq (.observed.resources.versioning | getResourceCondition "Synced").Status "True" }}
                gotemplating.fn.crossplane.io/ready: "True"
                {{- end }}
            data:
              {{- .observed.composite.resource.spec.kratix | toYaml | nindent 2 }}
              {{- if eq (.observed.resources.versioning | getResourceCondition "Synced").Status "True" }}
              state: ready
              {{- else }}
              state: degraded
              {{- end }}
              lastRun: {{ now | unixEpoch }}
              {{- with .observed.resources.versioning.status.atProvider }}
              details:
                {{- . | toYaml | nindent 4 }}
              {{- end }}
    - step: kratix-health-record-policy
      functionRef:
        name: fn-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: platform.kratix.io/v1alpha1
            kind: HealthRecord
            metadata:
              name: {{ .observed.composite.resource.metadata.name }}-policy
              annotations:
                {{ setResourceNameAnnotation "health-record-policy" }}
                {{- if eq (.observed.resources.policy | getResourceCondition "Synced").Status "True" }}
                gotemplating.fn.crossplane.io/ready: "True"
                {{- end }}
            data:
              {{- .observed.composite.resource.spec.kratix | toYaml | nindent 2 }}
              {{- if eq (.observed.resources.policy | getResourceCondition "Synced").Status "True" }}
              state: ready
              {{- else }}
              state: degraded
              {{- end }}
              lastRun: {{ now | unixEpoch }}
              {{- with .observed.resources.policy.status.atProvider }}
              details:
                {{- . | toYaml | nindent 4 }}
              {{- end }}
    - step: auto-ready
      functionRef:
        name: fn-auto-ready
