#!/bin/sh

set -xe

name=$(yq eval '.metadata.name' /kratix/input/object.yaml)

cat <<EOF > /kratix/metadata/status.yaml
healthStatus:
  state: unknown
EOF

cat <<EOF > /kratix/output/composite.yaml
apiVersion: crossplane.jkroepke.de/v1alpha1
kind: S3
metadata:
  name: $(yq eval '.spec.name' /kratix/input/object.yaml)
spec:
  providerConfigRef:
    kind: $(yq eval '.spec.providerConfigRef.kind' /kratix/input/object.yaml)
    name: $(yq eval '.spec.providerConfigRef.name' /kratix/input/object.yaml)
  kratix:
    promiseRef:
      name: s3
    resourceRef:
      name: $(yq eval '.spec.name' /kratix/input/object.yaml)
      namespace: $(yq eval '.spec.namespace' /kratix/input/object.yaml)
EOF
