ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: localhost
      paths:
        - path: /dex/
          pathType: Prefix

config:
  issuer: http://dex.dex.svc.cluster.local/dex
  enablePasswordDB: true
  storage:
    type: kubernetes
    config:
      inCluster: true
  oauth2:
    responseTypes: [ "code" ]
    skipApprovalScreen: true
    alwaysShowLoginScreen: false
  staticClients:
    - id: argocd
      name: 'Argo CD'
      secret: argocd
  staticPasswords:
    - email: "demo@example.com"
      # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      username: "demo"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
