persistence:
  enabled: true

strategy:
  type: Recreate

gitea:
  config:
    actions:
      ENABLED: false
    indexer:
      REPO_INDEXER_ENABLED: true
    server:
      ROOT_URL: http://localhost/git/
      LOCAL_ROOT_URL: http://forgejo-http.forgejo.svc.cluster.local:3000/git/
      START_SSH_SERVER: true
      SSH_PORT: 2222
      OFFLINE_MODE: true
    session:
      PROVIDER: db
      DOMAIN: localhost
  oauth:
    - name: 'sso'
      provider: 'openidConnect'
      key: 'forgejo'
      secret: 'forgejo'
      autoDiscoverUrl: 'http://localhost/git/dex/.well-known/openid-configuration'
      scopes: "openid email profile"
      groupClaimName: email
      adminGroup: 'demo@example.com'

service:
  http:
    port: 3000
  ssh:
    port: 2222

extraContainers:
  - name: dex
    image: ghcr.io/dexidp/dex:v2.44.0
    imagePullPolicy: IfNotPresent
    args:
      - dex
      - serve
      - "--web-http-addr"
      - 0.0.0.0:80
      - /etc/dex/config.yaml
    ports:
      - containerPort: 5556
        name: dex
        protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz/ready
        port: telemetry
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz/live
        port: telemetry
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    volumeMounts:
      - mountPath: /etc/dex
        name: dex-config
        readOnly: true

extraVolumes:
  - name: dex-config
    configMap:
      name: dex

extraDeploy:
  - |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: dex
      data:
        config.yaml: |
          issuer: http://localhost/git/dex
          connectors:
          - type: oidc
            id: sso
            name: SSO
            config:
              issuer: http://dex.dex.svc.cluster.local:5556/dex
              clientID: forgejo
              clientSecret: forgejo
              insecureSkipEmailVerified: true
              getUserInfo: false
              providerDiscoveryOverrides:
                authURL: http://localhost/git/dex/auth
          staticClients:
            - id: forgejo
              name: 'forgejo'
              secret: forgejo
              redirectURIs:
                - 'http://localhost/git/user/oauth2/sso/callback'

ingress:
  enabled: true
  className: "nginx"
  annotations:
    forecastle.stakater.com/expose: 'true'
    forecastle.stakater.com/appName: 'Forgejo'
    forecastle.stakater.com/url: 'http://localhost/git/'
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: $1
  hosts:
    - host: localhost
      paths:
        - path: "/git(/.*)"
          pathType: ImplementationSpecific
        - path: "/git/dex/"
          pathType: Prefix
          port: dex
