persistence:
  enabled: true

strategy:
  type: Recreate

gitea:
  admin:
    username: 'demo'
    password: 'password'
    email: 'demo@example.com'
  config:
    actions:
      ENABLED: false
    indexer:
      REPO_INDEXER_ENABLED: true
    server:
      ROOT_URL: http://localhost/git/
      LOCAL_ROOT_URL: http://forgejo-http.forgejo.svc.cluster.local:3000/
      START_SSH_SERVER: true
      SSH_PORT: 2222
      OFFLINE_MODE: true
    repository:
      ENABLE_PUSH_CREATE_USER: true
      ENABLE_PUSH_CREATE_ORG: true
    session:
      PROVIDER: db
      DOMAIN: localhost
    service:
      ALLOW_ONLY_EXTERNAL_REGISTRATION: true
      ENABLE_INTERNAL_SIGNIN: true
  oauth:
    - name: 'sso'
      provider: 'openidConnect'
      key: 'forgejo'
      secret: 'forgejo'
      autoDiscoverUrl: 'http://dex-proxy.dex.svc.cluster.local:8080/dex/.well-known/openid-configuration'
      scopes: "openid email profile"
      groupClaimName: email
      adminGroup: 'demo@example.com'

service:
  http:
    port: 3000
  ssh:
    port: 2222

ingress:
  enabled: true
  className: "nginx"
  annotations:
    forecastle.stakater.com/expose: 'true'
    forecastle.stakater.com/appName: 'Forgejo'
    forecastle.stakater.com/url: 'http://localhost/git/'
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: $1
  hosts:
    - host: localhost
      paths:
        - path: "/git(/.*)"
          pathType: ImplementationSpecific
