createAggregateRoles: true
crds:
  install: true

global:
  domain: localhost

configs:
  cm:
    create: true
    annotations: {}
    # -- Enable control of the service account used for the sync operation (alpha)
    ## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/app-sync-using-impersonation/
    application.sync.impersonation.enabled: false
    # -- Enable logs RBAC enforcement
    ## Ref: https://argo-cd.readthedocs.io/en/latest/operator-manual/upgrading/2.3-2.4/#enable-logs-rbac-enforcement
    server.rbac.log.enforce.enable: false
    # -- Enable exec feature in Argo UI
    ## Ref: https://argo-cd.readthedocs.io/en/latest/operator-manual/rbac/#exec-resource
    exec.enabled: true
    # -- Enable local admin user
    ## Ref: https://argo-cd.readthedocs.io/en/latest/faq/#how-to-disable-admin-user
    admin.enabled: false
    # OIDC configuration as an alternative to dex (optional).
    # Dex configuration
    url: http://localhost/argo-cd
    dex.config: |
      connectors:
        - type: oauth
          id: sso
          name: SSO
          config:
            clientID: argocd
            clientSecret: argocd
          # redirectURI: http://127.0.0.1:5556/callback
          tokenURL: http://dex.dex.svc.cluster.local:5556/dex/token
          authorizationURL: http://localhost/dex/auth
          userInfoURL: http://dex.dex.svc.cluster.local:5556/dex/userinfo
dex:
  enabled: true

server:
  extraArgs:
    - --insecure
    - --rootpath=/argo-cd
  ingress:
    enabled: true
    ingressClassName: "nginx"
    paths:
      - "/argo-cd/"
    pathType: Prefix
    tls: false
