createAggregateRoles: true
crds:
  install: true

global:
  domain: localhost

configs:
  cm:
    create: true
    annotations: {}
    application.resourceTrackingMethod: annotation
    resource.exclusions: |
      - apiGroups:
        - "*"
        kinds:
        - ProviderConfigUsage
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/reconcile/#argoprojioapplication
    resource.customizations.ignoreResourceUpdates.argoproj.io_Application: |
      jsonPointers:
      # Ignore when ownerReferences change, for example when a parent ApplicationSet changes often.
      - /metadata/ownerReferences
      # Ignore reconciledAt, since by itself it doesn't indicate any important change.
      - /status/reconciledAt
      jqPathExpressions:
      # Ignore lastTransitionTime for conditions; helpful when SharedResourceWarnings are being regularly updated but not
      # actually changing in content.
      - .status?.conditions[]?.lastTransitionTime
    resource.customizations: |
      "*.upbound.io/*":
        health.lua: |
          health_status = {
            status = "Progressing",
            message = "Provisioning ..."
          }
  
          local function contains (table, val)
            for i, v in ipairs(table) do
              if v == val then
                return true
              end
            end
            return false
          end
  
          local has_no_status = {
            "ClusterProviderConfig",
            "ProviderConfig",
            "ProviderConfigUsage"
          }
  
          if obj.status == nil or next(obj.status) == nil and contains(has_no_status, obj.kind) then
            health_status.status = "Healthy"
            health_status.message = "Resource is up-to-date."
            return health_status
          end
  
          if obj.status == nil or next(obj.status) == nil or obj.status.conditions == nil then
            if (obj.kind == "ProviderConfig" or obj.kind == "ClusterProviderConfig") and obj.status.users ~= nil then
              health_status.status = "Healthy"
              health_status.message = "Resource is in use."
              return health_status
            end
            return health_status
          end
  
          for i, condition in ipairs(obj.status.conditions) do
            if condition.type == "LastAsyncOperation" then
              if condition.status == "False" then
                health_status.status = "Degraded"
                health_status.message = condition.message
                return health_status
              end
            end
  
            if condition.type == "Synced" then
              if condition.status == "False" then
                health_status.status = "Degraded"
                health_status.message = condition.message
                return health_status
              end
            end
  
            if condition.type == "Ready" then
              if condition.status == "True" then
                health_status.status = "Healthy"
                health_status.message = "Resource is up-to-date."
                return health_status
              end
            end
          end
  
          return health_status
  
      "*.crossplane.io/*":
        health.lua: |
          health_status = {
            status = "Progressing",
            message = "Provisioning ..."
          }
  
          local function contains (table, val)
            for i, v in ipairs(table) do
              if v == val then
                return true
              end
            end
            return false
          end
  
          local has_no_status = {
            "Composition",
            "CompositionRevision",
            "DeploymentRuntimeConfig",
            "ClusterProviderConfig",
            "ProviderConfig",
            "ProviderConfigUsage"
          }
          if obj.status == nil or next(obj.status) == nil and contains(has_no_status, obj.kind) then
              health_status.status = "Healthy"
              health_status.message = "Resource is up-to-date."
            return health_status
          end
  
          if obj.status == nil or next(obj.status) == nil or obj.status.conditions == nil then
            if (obj.kind == "ProviderConfig" or obj.kind == "ClusterProviderConfig") and obj.status.users ~= nil then
              health_status.status = "Healthy"
              health_status.message = "Resource is in use."
              return health_status
            end
            return health_status
          end
  
          for i, condition in ipairs(obj.status.conditions) do
            if condition.type == "LastAsyncOperation" then
              if condition.status == "False" then
                health_status.status = "Degraded"
                health_status.message = condition.message
                return health_status
              end
            end
  
            if condition.type == "Synced" then
              if condition.status == "False" then
                health_status.status = "Degraded"
                health_status.message = condition.message
                return health_status
              end
            end
  
            if contains({"Ready", "Healthy", "Offered", "Established", "ValidPipeline", "RevisionHealthy"}, condition.type) then
              if condition.status == "True" then
                health_status.status = "Healthy"
                health_status.message = "Resource is up-to-date."
                return health_status
              end
            end
          end
  
          return health_status
      "platform.kratix.io/*":
        health.lua: |
          health_status = {
            status = "Progressing",
            message = "Provisioning ..."
          }
      
          local function contains (table, val)
            for i, v in ipairs(table) do
              if v == val then
                return true
              end
            end
            return false
          end
      
          local has_no_status = {
            "HealthRecord"
          }
      
          if contains(has_no_status, obj.kind) then
            health_status.status = "Healthy"
            health_status.message = "Resource is up-to-date."
            return health_status
          end
      
          if obj.status == nil or obj.status.conditions == nil then
            return health_status
          end
      
          for i, condition in ipairs(obj.status.conditions) do
            if condition.status == "False" then
              health_status.status = "Degraded"
              health_status.message = condition.message
              return health_status
            end
          end
      
          if obj.status.status == "Available" then
            health_status.status = "Healthy"
            health_status.message = "Resource is up-to-date."
            return health_status
          end
      
          return health_status

    # -- Enable control of the service account used for the sync operation (alpha)
    ## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/app-sync-using-impersonation/
    application.sync.impersonation.enabled: false
    # -- Enable logs RBAC enforcement
    ## Ref: https://argo-cd.readthedocs.io/en/latest/operator-manual/upgrading/2.3-2.4/#enable-logs-rbac-enforcement
    server.rbac.log.enforce.enable: false
    # -- Enable exec feature in Argo UI
    ## Ref: https://argo-cd.readthedocs.io/en/latest/operator-manual/rbac/#exec-resource
    exec.enabled: true
    # -- Enable local admin user
    ## Ref: https://argo-cd.readthedocs.io/en/latest/faq/#how-to-disable-admin-user
    admin.enabled: false
    # OIDC configuration as an alternative to dex (optional).
    # Dex configuration
    url: http://localhost:8400/argo-cd
    oidc.config: |
      name: SSO
      issuer: http://dex-proxy.dex.svc.cluster.local:8080/dex
      clientID: argocd
      clientSecret: argocd
      requestedScopes: ["openid", "profile", "email", "groups"]
      enablePKCEAuthentication: true
  rbac:
    # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md#using-sso-usersgroups
    create: true
    policy.default: 'role:unauthenticated'
    policy.csv: |-
      g, demo@example.com, role:admin
    scopes: '[groups, email]'
dex:
  enabled: false

server:
  extraArgs:
    - --insecure
    - --rootpath=/argo-cd
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      forecastle.stakater.com/expose: 'true'
      forecastle.stakater.com/appName: 'Argo CD'
    path: "/argo-cd/"
    pathType: Prefix
    tls: false
